### ISSUE TITLE
Support for Symfony's "authenticator manager" and CSRF

### ISSUE THREAD

**Issue by weaverryan** [netgen-layouts/layouts-core#28]
Hi!

I think we've talked about this in a different channel before, but I don't think that layouts (yet) supports the new "authenticator system: (i.e. `enable_authenticator_manager: true` in `security.yaml`). If it's set to true, then while working on a layout, I sometimes see a CSRF failed error:

<img width="444" alt="Screen Shot 2022-08-24 at 3 55 03 PM" src="https://user-images.githubusercontent.com/121003/186510961-41408244-a4d4-4d98-b5fd-72709a8034eb.png">

This occurred after modifying that `query.doctrine_search.title` field (that's from a custom query type I have).

Cheers!

**Comment by emodric** [comment]
Hi @weaverryan !

Yeah, no support for `enable_authenticator_manager: true` yet. The main reason why support is not yet implemented is that Netgen Layouts, due to Netgen's own needs, still supports Symfony 3.4 and 4.4, so new authentication manager is not yet a priority.

**Comment by emodric** [comment]
@weaverryan I suppose you'd wanna know that I managed to get Layouta running on Symfony 6, but so far no issues with authentication manager. I will test further though.
