### ISSUE TITLE
[BC break] \Netgen\Layouts\API\Service\BlockService::loadPlaceholderBlocks added

### ISSUE THREAD

**Issue by dkarlovi** [netgen-layouts/layouts-core#31]
New method `\Netgen\Layouts\API\Service\BlockService::loadPlaceholderBlocks` introduced in non-major release.

**Comment by emodric** [comment]
Ugh, right, I forgot about this one!

Fixed now in `1.4.2`. Thanks @dkarlovi !

**Comment by dkarlovi** [comment]
@emodric tnx, živio. :rocket:
